# Generated by Django 3.1.2 on 2020-11-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last',
            new_name='last_name',
        ),
    ]
