# Generated by Django 3.1.2 on 2020-11-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0002_auto_20201121_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchedlist',
            field=models.ManyToManyField(related_name='watchedlist', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to='movies.Movie'),
        ),
    ]
