# Generated by Django 3.1.2 on 2021-01-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210106_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerrelation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
    ]
