# Generated by Django 3.1.2 on 2021-03-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210306_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerRelation',
        ),
    ]
