# Generated by Django 3.1.2 on 2021-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_remove_actor_image'),
        ('movies', '0007_auto_20210303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(blank=True, to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Genre',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Ratings',
            field=models.ManyToManyField(blank=True, to='movies.Rating'),
        ),
    ]
