# Generated by Django 3.1.2 on 2021-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
