# Generated by Django 3.1.2 on 2021-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='imdb_id',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='url_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
