# Generated by Django 3.1.2 on 2021-03-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210312_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
