# Generated by Django 3.1.2 on 2021-03-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='date',
        ),
    ]
