# Generated by Django 3.1.2 on 2021-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210324_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
    ]
