# Generated by Django 3.1.2 on 2021-03-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
    ]
