# Generated by Django 3.1.2 on 2021-04-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210303_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='timestamp',
        ),
    ]
